// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Core = require("@material-ui/core");

function PublicationHeader(Props) {
  return React.createElement(Core.Box, {
              children: React.createElement(Core.Typography, {
                    align: "center",
                    children: "dictyBase Literature",
                    variant: "h2"
                  }),
              mb: 2,
              mt: 2
            });
}

var make = PublicationHeader;

exports.make = make;
/* react Not a pure module */
