// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Utils from "../../common/utils/utils.bs.js";
import * as ApolloClient from "rescript-apollo-client/src/ApolloClient.bs.js";
import * as ApolloClient__Cache_InMemory_InMemoryCache from "rescript-apollo-client/src/@apollo/client/cache/inmemory/ApolloClient__Cache_InMemory_InMemoryCache.bs.js";

var client = ApolloClient.make((function (param) {
        return Utils.Env.getVariable("NEXT_PUBLIC_GRAPHQL_SERVER");
      }), undefined, undefined, undefined, ApolloClient__Cache_InMemory_InMemoryCache.make(undefined, undefined, undefined, undefined, undefined, undefined), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);

export {
  client ,
  
}
/* client Not a pure module */
