// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var ApolloClient = require("rescript-apollo-client/src/ApolloClient.bs.js");
var ApolloClient__Cache_InMemory_InMemoryCache = require("rescript-apollo-client/src/@apollo/client/cache/inmemory/ApolloClient__Cache_InMemory_InMemoryCache.bs.js");

var client = ApolloClient.make((function (param) {
        return "https://ericgraphql.dictybase.dev";
      }), undefined, undefined, undefined, ApolloClient__Cache_InMemory_InMemoryCache.make(undefined, undefined, undefined, undefined, undefined, undefined), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);

exports.client = client;
/* client Not a pure module */
