// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_exn from "rescript/lib/es6/js_exn.js";
import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as Process from "process";

var nodeEnv = Process.env;

function getVariable(name) {
  var value = Js_dict.get(nodeEnv, name);
  if (value !== undefined) {
    return value;
  } else {
    return Js_exn.raiseError("Environment variable " + name + " is missing");
  }
}

var Env = {
  nodeEnv: nodeEnv,
  getVariable: getVariable
};

export {
  Env ,
  
}
/* nodeEnv Not a pure module */
