// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Js_exn = require("rescript/lib/js/js_exn.js");
var Js_dict = require("rescript/lib/js/js_dict.js");
var Process = require("process");

var nodeEnv = Process.env;

function getVariable(name) {
  var value = Js_dict.get(nodeEnv, name);
  if (value !== undefined) {
    return value;
  } else {
    return Js_exn.raiseError("Environment variable " + name + " is missing");
  }
}

var Env = {
  nodeEnv: nodeEnv,
  getVariable: getVariable
};

exports.Env = Env;
/* nodeEnv Not a pure module */
